AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is a lambda service that returns optimiser commercial times
Resources:
  GetOptimiserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Optimiser::Optimiser.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: s3://optimiser-api/d8c3bf9cb6f3eea9f3b3dbab3644cd35
      Policies:
      - AmazonDynamoDBFullAccess
      Timeout: 60
      MemorySize: 3008
      Environment:
        Variables:
          S3_BUCKET: optimisercfsambucket
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  Break:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: N
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: Break
  Commercial:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: N
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '4'
        WriteCapacityUnits: '4'
      TableName: Commercial
