AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is a lambda service that returns optimiser commercial times
Resources:
  GetOptimiserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Optimiser::Optimiser.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: s3://optimiser-api/6b65b4503d74389b9746150255ec22fd
      Policies:
      - AmazonDynamoDBFullAccess
      Timeout: 60
      MemorySize: 3008
      Environment:
        Variables:
          S3_BUCKET: optimisercfsambucket
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
